/* eslint-disable @typescript-eslint/no-require-imports -- Browser acceptance test. */
const {chromium}=require(process.env.ONE_G_PLAYWRIGHT||'playwright-core');
const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.ONE_G_TEST_URL||'http://localhost:3000/one-g';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.ONE_G_BROWSER});const errors=[],privateRequests=[];const dir='/tmp/one-contact-review';fs.mkdirSync(dir,{recursive:true});
const context=await browser.newContext();const p=await context.newPage();p.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url())});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'){if(m.location().url===new URL(base).origin+'/favicon.ico')console.log('Known unrelated root favicon 404');else errors.push(m.text());}if(m.text().includes('PRIVATE_TEST'))privateRequests.push('console');});p.on('request',r=>{if((r.method()==='POST'&&!r.url().includes('/_next/'))||r.postData()?.includes('PRIVATE_TEST')||/\/api\/(contact|support|mail)/.test(r.url())||r.url().includes('PRIVATE_TEST'))privateRequests.push(r.url());});
const dialog=()=>p.getByRole('dialog');const mode=async m=>p.waitForFunction(m=>document.documentElement.dataset.theme===m,m);
const login=async(account='19900000001')=>{await p.getByLabel('手机号',{exact:true}).fill(account);await p.getByRole('button',{name:'登录 ONE-G（演示）',exact:true}).click();};
const open=async entry=>{await p.locator(`button[data-contact-entry="${entry}"]`).click();await dialog().waitFor();};
const close=async()=>{await dialog().getByRole('button',{name:'关闭需求窗口'}).click();await dialog().waitFor({state:'detached'});};
try{
await p.goto(base+'/about/?openContact=about');assert.equal(await dialog().count(),0);assert.equal(await p.locator('a[href^="tel:"],a[href^="mailto:"]').count(),0);assert.equal(await p.getByText('400-XXX-XXXX').count(),0);assert.equal(await p.getByText('service@one-g.com').count(),0);
await p.locator('button[data-contact-entry="about"]').click();await p.waitForURL('**/login/**');assert.ok(new URL(p.url()).searchParams.get('returnTo').includes('/about'));await login();await p.waitForURL('**/about/**');await dialog().waitFor();assert.equal(new URL(p.url()).searchParams.has('openContact'),false);assert.equal(await p.locator('#contact-name').evaluate(e=>e===document.activeElement),true);
await dialog().getByRole('button',{name:'预览需求',exact:true}).click();await p.getByText('请填写称呼。',{exact:true}).waitFor();await p.getByText('请填写需求描述。',{exact:true}).waitFor();await p.locator('#contact-name').fill('PRIVATE_TEST 测试称呼');await p.locator('#contact-email').fill('bad');await p.locator('#contact-description').fill('PRIVATE_TEST 测试需求\n第二行');await dialog().getByRole('button',{name:'预览需求',exact:true}).click();await p.getByText('请填写有效的回复邮箱。',{exact:true}).waitFor();await p.locator('#contact-email').fill('PRIVATE_TEST@example.test');await p.locator('#contact-company').fill('PRIVATE_TEST 测试单位');
await p.setViewportSize({width:1440,height:1000});await p.screenshot({path:dir+'/desktop-form.png'});await dialog().getByRole('button',{name:'预览需求',exact:true}).click();await p.getByText('仅供预览，尚未提交。',{exact:true}).waitFor();assert.ok((await dialog().textContent()).includes('PRIVATE_TEST 测试单位'));assert.ok((await dialog().textContent()).includes('About 咨询'));await p.screenshot({path:dir+'/desktop-preview.png'});await dialog().getByRole('button',{name:'返回编辑'}).click();assert.equal(await p.locator('#contact-name').inputValue(),'PRIVATE_TEST 测试称呼');
assert.equal(await p.evaluate(()=>JSON.stringify({...localStorage}).includes('PRIVATE_TEST')),false);assert.equal(p.url().includes('PRIVATE_TEST'),false);
await p.setViewportSize({width:390,height:844});await p.screenshot({path:dir+'/mobile-form.png'});const rect=await dialog().boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=390);await close();assert.equal(await p.locator('button[data-contact-entry="about"]').evaluate(e=>e===document.activeElement),true);await p.locator('section[aria-labelledby="contact-title"]').scrollIntoViewIfNeeded();await p.screenshot({path:dir+'/mobile-about.png'});await open('about');assert.equal(await p.locator('#contact-name').inputValue(),'');await p.keyboard.press('Escape');await dialog().waitFor({state:'detached'});
await p.setViewportSize({width:1440,height:1000});await p.locator('section[aria-labelledby="contact-title"]').scrollIntoViewIfNeeded();await p.screenshot({path:dir+'/desktop-about.png'});
// Session changes from another tab must destroy private draft state immediately.
await open('about');await p.locator('#contact-name').fill('PRIVATE_TEST previous user');await p.evaluate(()=>{localStorage.setItem('one-g-auth-demo',JSON.stringify({version:1,userId:'user-demo-b'}));dispatchEvent(new StorageEvent('storage',{key:'one-g-auth-demo'}));});await dialog().waitFor({state:'detached'});await open('about');assert.equal(await p.locator('#contact-name').inputValue(),'');await p.evaluate(()=>{localStorage.removeItem('one-g-auth-demo');dispatchEvent(new StorageEvent('storage',{key:'one-g-auth-demo'}));});await dialog().waitFor({state:'detached'});
// Each protected action restores the original page and purchase query, not a submission.
for(const [route,entry,source]of [['/solutions/#handling','solutions','解决方案咨询'],['/deep-customization/?product=robotdock&package=base&quantity=2&payment=alipay','deep','深度定制需求']]){
 await p.goto(base+route);await p.locator(`button[data-contact-entry="${entry}"]`).click();await p.waitForURL('**/login/**');await login();await dialog().waitFor();assert.ok((await dialog().textContent()).includes(source));if(entry==='solutions'){assert.equal(new URL(p.url()).hash,'#handling');assert.ok((await dialog().textContent()).includes('搬运'));}if(entry==='deep'){const u=new URL(p.url());for(const[k,v]of Object.entries({product:'robotdock',package:'base',quantity:'2',payment:'alipay'}))assert.equal(u.searchParams.get(k),v);assert.ok((await dialog().textContent()).includes('RobotDock'));await close();const back=p.getByRole('link',{name:'← 返回购买'});assert.ok((await back.getAttribute('href')).includes('/one-g/buy/robotdock'));}else await close();await p.goto(base+'/account/');await p.getByRole('button',{name:'退出登录',exact:true}).click();await p.waitForURL(base+'/');await p.waitForLoadState('networkidle');
}
await p.goto(base+'/login/');await login();await p.waitForURL('**/account/');await open('account');await p.locator('#contact-name').fill('PRIVATE_TEST reload draft');await p.reload();await p.locator('main h1').waitFor();assert.equal(await dialog().count(),0);await open('account');assert.equal(await p.locator('#contact-name').inputValue(),'');await close();await open('footer-contact');await close();assert.equal(await p.locator('a[href^="tel:"],a[href^="mailto:"]').count(),0);
for(const [id,name]of [['eye-comfort','护眼模式'],['night','夜间模式'],['color-vision-safe','色觉友好'],['standard','标准显示']]){await p.getByRole('button',{name:'显示设置',exact:true}).click();const panel=p.locator('#header-accessibility');if(id==='standard')await panel.getByRole('button',{name:'恢复标准',exact:true}).click();else await panel.getByRole('switch',{name,exact:true}).check();await mode(id);await p.keyboard.press('Escape');await open('account');await p.keyboard.press('Tab');assert.ok(await dialog().evaluate(e=>e.contains(document.activeElement)));await close();}
await p.getByRole('button',{name:'退出登录',exact:true}).click();await p.waitForURL(base+'/');await p.waitForLoadState('networkidle');await p.setViewportSize({width:390,height:844});await p.goto(base+'/about/');await p.locator('footer').getByRole('button',{name:'账户与服务',exact:true}).click();await p.locator('[data-contact-entry="footer-help"]').click();await p.waitForURL('**/login/**');await login();await dialog().waitFor();await close();assert.equal(await p.locator('[data-contact-entry="footer-help"]').evaluate(e=>e===document.activeElement),true);
assert.deepEqual(errors,[]);assert.deepEqual(privateRequests,[]);console.log('PASS About public/action login, return/open once, validation, preview/edit/clear, focus/Escape, mobile, account changes, solutions/deep context, Footer/account shared form, no private storage/network/console or hydration errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
