/* eslint-disable @typescript-eslint/no-require-imports -- Browser regression. */
const {chromium}=require('/tmp/one-g-route-check/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page.setDefaultTimeout(20000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const base=process.env.ONE_G_TEST_URL||'http://localhost:3000/one-g';
 async function go(route){let res;try{res=await page.goto(base+route)}catch(e){if(!String(e).includes('ERR_ABORTED'))throw e;res=await page.goto(base+route)}assert.equal(res.status(),200,route);await page.locator('h1').first().waitFor({state:'attached'});await page.waitForTimeout(300);}
 for(const route of ['/','/about/','/solutions/','/deep-customization/','/configure/','/products/','/products/arm-a1/','/products/robotdock/','/products/sonic-link/']){await go(route);assert.ok(!page.url().includes('/login'),route);}
 await go('/');assert.deepEqual(await page.getByRole('navigation',{name:'主导航',exact:true}).getByRole('link').evaluateAll(a=>a.map(x=>x.getAttribute('href'))),['/one-g/configure/','/one-g/solutions/','/one-g/products/','/one-g/about/']);assert.equal(await page.getByRole('link',{name:'购物车',exact:true}).first().getAttribute('href'),'/one-g/login/?returnTo=%2Fcart');
 for(const route of ['/cart','/checkout','/account','/order-success']){await page.goto(base+route+'/');await page.waitForURL('**/login/**');assert.equal(new URL(page.url()).searchParams.get('returnTo'),route);}
 await page.goto(base+'/admin/');await page.waitForURL('**/admin/login/**');
 for(const route of ['/configure/robot/','/configure/robotdock/','/configure/sonic-link/','/customize/','/customize/start/']){await page.goto(base+route);await page.waitForURL('**/one-g/configure/');}
 await go('/deep-customization/');await page.getByRole('button',{name:'提交深度定制需求',exact:true}).click();await page.locator('a[href^="mailto:"]').waitFor();assert.ok(!page.url().includes('/login'));
 await go('/products/arm-a1/?source=test#buy');await page.getByRole('button',{name:'加入购物车',exact:true}).click();await page.waitForURL('**/login/**');assert.equal(new URL(page.url()).searchParams.get('returnTo'),'/products/arm-a1?source=test#buy');assert.equal(await page.evaluate(()=>localStorage.getItem('one-g-cart')),null);assert.equal(await page.evaluate(()=>JSON.parse(sessionStorage.getItem('one-g-pending-cart-action')).action),'add-to-cart');
 await page.locator('input[name="email"]').fill('user@one-g.com');await page.locator('input[name="password"]').fill('123456');await page.locator('form button[type="submit"]').click();await page.waitForURL('**/products/arm-a1/**');await page.getByRole('status').filter({hasText:'登录成功，请继续加入购物车。'}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('one-g-cart')),null);
 await page.getByRole('button',{name:'加入购物车',exact:true}).click();await page.getByRole('button',{name:'已加入购物车',exact:true}).waitFor();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('one-g-cart'))),[{productId:'arm-a1',quantity:1}]);await page.reload();assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('one-g-cart'))),[{productId:'arm-a1',quantity:1}]);await go('/cart/');await go('/account/');
 for(const theme of ['caribbean-calcite','night','color-vision-safe']){await page.evaluate(t=>{localStorage.setItem('one-g-theme:user-demo',t==='color-vision-safe'?'night':t);localStorage.setItem('one-g-accessibility-theme',t==='color-vision-safe'?t:'null');},theme);for(const route of ['/solutions/','/deep-customization/']){await go(route);await page.waitForFunction(t=>document.documentElement.dataset.theme===t,theme);await page.waitForTimeout(400);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}
 for(const width of [375,390,768,1440]){await page.setViewportSize({width,height:900});await go('/solutions/');assert.equal(await page.locator('main article').count(),4);const filters=page.getByRole('group',{name:'解决方案分类'});await filters.getByRole('button').nth(2).click();assert.equal(await page.locator('main article').count(),1);await filters.getByRole('button').first().click();await page.getByRole('button',{name:'查看方案 +',exact:true}).first().click();assert.equal(await page.locator('main button[aria-expanded="true"]').count(),1);await page.getByText('适用边界',{exact:true}).first().waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.next/access-solutions-'+width+'.png',fullPage:true});await go('/deep-customization/');assert.equal(await page.locator('main ol li').count(),4);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width<768){const boxes=await page.locator('main ol li').evaluateAll(items=>items.map(x=>x.getBoundingClientRect().y));assert.ok(boxes.every((y,i)=>i===0||y>boxes[i-1]));}await page.screenshot({path:'.next/access-deep-'+width+'.png',fullPage:true});}
 assert.deepEqual(errors,[]);console.log('PASS public browsing, private/admin guards, no anonymous cart, login returnTo + pending hint, manual add once, legacy redirects, three themes and mobile solutions/deep customization');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
